FROM {{ image_spec("base-tools") }}
MAINTAINER {{ maintainer }}

COPY {{ render('sources.list.debian.j2') }} /etc/apt/sources.list.d/percona.list
COPY {{ render('apt_preferences.debian.j2') }} /etc/apt/preferences
COPY percona_sudoers /etc/sudoers.d/percona_sudoers

RUN apt-key adv --recv-keys --keyserver {{ url.percona.debian.keyserver }} \
    {{ url.percona.debian.keyid }} \
    && apt-get update \
    && apt-get install -y --force-yes --no-install-recommends percona-xtradb-cluster-57 jq \
    && pip install --no-cache-dir pymysql \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/percona_sudoers \
    && usermod -a -G microservices mysql \
    && chown -R mysql: /etc/mysql

USER mysql
