FROM {{ namespace }}/base-tools:{{ tag }}
MAINTAINER {{ maintainer }}

ENV DEBIAN_FRONTEND noninteractive

COPY galera-healthcheck /usr/bin/galera-healthcheck

RUN chmod a+x /usr/bin/galera-healthcheck

EXPOSE 8080
